### ISSUE TITLE
Add to command palette

### ISSUE THREAD

**Issue by jamie9090** [heliostatic/completed-task-display#7]
Possible to add to Obsidian commands for potential hot keys, or using command palette? 

I don't use the ribbon at the moment due to Minimal Theme, so this would be awesome!

**Comment by kmcelwee** [comment]
Just finished this feature! @heliostatic let me know if you need me to make any changes ☺️

**Comment by heliostatic** [comment]
> Just finished this feature! @heliostatic let me know if you need me to make any changes ☺️

Thanks! I'll review and merge tonight.

**Comment by kmcelwee** [comment]
Hi @heliostatic! Do you need me to change anything?

**Comment by tonyxiao** [comment]
hey folks could this be merged in and released? Would love to be able to use the keyboard for this.

**Comment by heliostatic** [comment]
Merged

**Comment by tonyxiao** [comment]
Fantastic! Could you make a new release for it?
